pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        deployment: Test
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:saf-gobnay/app-servicio-publico.git
          - cd app-servicio-publico.git
          - git push --mirror git@github.com:dgsiDevPaula/SEMOVINAY.git